export const FETCH_TEMPERTURE_START = 'FETCH_TEMPERTURE_START';
export const FETCH_TEMPERTURE_SUCCESS = 'FETCH_TEMPERTURE_SUCCESS';
export const FETCH_TEMPERTURE_FAILURE = 'FETCH_TEMPERTURE_FAILURE';
